[server]
maxUploadSize = 5
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
enableSecureConnection = false

[runner]
memory_limit = "1000M"

[theme]
base = "dark"
primaryColor = "#4C61F0"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"

[client]
showErrorDetails = false
caching = true
