[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501
enableSecureConnection = false

[runner]
magicEnabled = false
fastRerenderEnabled = false

[theme]
base = "dark"

[client]
showErrorDetails = false
caching = true
